### ISSUE TITLE
Support for Twig 2

### ISSUE THREAD

**Issue by TheCelavi** [symfony2admingenerator/FormBundle#10]
Is planned support for Twig 2?

**Comment by bobvandevijver** [comment]
Planned? No. Might it happen? Maybe.

**Comment by TheCelavi** [comment]
FormExtensionBundle depends on this bundle, and this bundle uses Twig 1.2.

It seams as if it would work with Twig 2.0 out of the box, but there are no tests to confirm... 

So, yeah, it will be tricky to upgrade, either tests ought to be added to codebase, or ... is there any other option?

**Comment by bobvandevijver** [comment]
I would say: try it, and report/solve the issues you find :) This bundle should be small enough to find the problems easy enough.

**Comment by sescandell** [comment]
Done
